### PR TITLE
PR For Issue #5 | Modified frontend

### PR DESCRIPTION
**Pull request by kailash360**
I have modified the frontend of the project.

### CODE REVIEW

**Comment by DebadityaPal** [comment]
Changes suggested, please take a look.

**Comment by kailash360** [comment]
Sir, can you kindly clarify on the changes suggested?

**Comment by DebadityaPal** [comment]
Just add `rel="noreferrer"` beside `target="_blank"` in the line with my GitHub URL. React gives a warning during compilation otherwise.

**Comment by DebadityaPal** [comment]
Actually, nvm, I'll add it. I'm merging this PR! Thanks for your contribution.

**Pull request merged**
