### PR TITLE
Responsive frontend

### LINKED ISSUE #2: [FEATURE] Responsive Frontend
Currently, the website is not responsive, ideally, the website should be accessible from both Desktop and Mobile users. 
Hence, we need it to be responsive.
The contributor can fully decide how they want the frontend to behave as long as the functionality is not lost.

### PR DESCRIPTION
**Pull request by gurpreet-legend**
Fixes #2 , @Debaditya-Pal please review sir

### CODE REVIEW

**Comment by DebadityaPal** [comment]
Hi @gurpreet-legend everything looks amazing! I just have one addition to ask of you.
Can you make the back button after clicking `check now` a fixed button on smaller screens that always stays at the bottom left position of the screen irrespective of where the user is scrolling?
That way the user wont have to scroll to the bottom to go back everytime.

**Comment by gurpreet-legend** [comment]
> Hi @gurpreet-legend everything looks amazing! I just have one addition to ask of you. Can you make the back button after clicking `check now` a fixed button on smaller screens that always stays at the bottom left position of the screen irrespective of where the user is scrolling? That way the user wont have to scroll to the bottom to go back everytime.

Done @Debaditya-Pal :)

**Comment by gurpreet-legend** [comment]
@Debaditya-Pal , sir any updates ?

**Comment by DebadityaPal** [comment]
LGTM, merging

**Pull request merged**
